### ISSUE TITLE
mod failed for 1.19 with forge 1.19 - 41.1.0

### ISSUE THREAD

**Issue by AleFrech** [TarantelTM/chicken_roost#5]
![image](https://user-images.githubusercontent.com/6412685/184057981-b9a424c4-e1ec-431f-b8e4-49f725d41fd5.png)

Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19-41.1.0-universal.jar%23252!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19-41.1.0-universal.jar%23252!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:561) ~[client-1.19-20220607.102129-srg.jar%23247!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:596) ~[client-1.19-20220607.102129-srg.jar%23247!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixin.imdlib-betteranimalsplus.json:UtilMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:555) ~[client-1.19-20220607.102129-srg.jar%23247!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:196) ~[client-1.19-20220607.102129-srg.jar%23247!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1290) ~[client-1.19-20220607.102129-srg.jar%23247!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1084) ~[client-1.19-20220607.102129-srg.jar%23247!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669) ~[client-1.19-20220607.102129-srg.jar%23247!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23247!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.1.0.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.tarantel.chickenroost.init.ChickenRoostModEntities.<clinit>(ChickenRoostModEntities.java:161) ~[roost_ultimate-1.19-0.2.7.jar%23230!/:?] {re:classloading}
-- MOD chicken_roost --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.1.0.jar%23249!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.1.0.jar%23248!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /.minecraft/mods/roost_ultimate-1.19-0.2.7.jar
	Failure message: Roost Ultimate (chicken_roost) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 0.2.7
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchFieldError: ENTITIES
Stacktrace:
	at net.tarantel.chickenroost.init.ChickenRoostModEntities.<clinit>(ChickenRoostModEntities.java:161) ~[roost_ultimate-1.19-0.2.7.jar%23230!/:?] {re:classloading}
	at net.tarantel.chickenroost.ChickenRoostMod.<init>(ChickenRoostMod.java:79) ~[roost_ultimate-1.19-0.2.7.jar%23230!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.1.0.jar%23249!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.1.0.jar%23248!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by TarantelTM** [comment]
Hello
Oh Optifine is already released for 1.19 ^^
Will check this out.
Its possible to send me a list of used mods too ?

**Comment by AleFrech** [comment]
Sure.

Mod List :

<html>
<body>


[1.19]+SecurityCraft+v1.9.2-beta6.jar | FramedBlocks-6.2.0.jar | polymorph-forge-0.45.0+1.19.1.jar
-- | -- | --
[1.19]-Epic-Knights-Armor-and-Weapons-5.12v.jar | geckolib-forge-1.19-3.1.9.jar | potionring-1.19-1.0.jar
alexsmobs-1.19.3.jar | Gobber2-Forge-1.19.0-2.7.6.jar | rechiseled-1.0.10c-forge-mc1.19.jar
AoA3-1.19-3.6.9.jar | goblintraders-1.7.3-1.19.jar | RingsOfAscension-1.19-1.0.1.jar
appleskin-forge-mc1.19-2.4.2.jar | InventoryProfilesNext-forge-1.19-1.6.0.jar | Runelic-Forge-1.19-12.1.3.jar
appliedenergistics2-12.0.2-alpha.jar | Jade-1.19-forge-7.6.0.jar | searchlight-1.19-forge-1.1.8.jar
Aquaculture-1.19-2.4.5.jar | jei-1.19-forge-11.1.1.239.jar | SimpleStorageNetwork-1.19-1.6.3.jar
architectury-5.10.33-forge.jar | journeymap-1.19-5.8.5-forge.jar | SimpleStorageNetwork-1.19-1.6.4.jar
AwesomeDungeonEnd-Forge-1.19-1.0.3.jar | kotlinforforge-3.6.0-obf.jar | simplylight-1.19-1.4.4-build.39.jar
AwesomeDungeon-Forge-1.19-2.0.11.jar | LibraryFerret-Forge-1.19-2.5.1.jar | sophisticatedbackpacks-1.19-3.17.13.628.jar
AwesomeDungeonNether-Forge-1.19-1.0.2.jar | mcw-bridges-2.0.3-mc1.19.jar | sophisticatedcore-1.19-0.3.9.63.jar
AwesomeDungeonOcean-Forge-1.19-2.0.7.jar | mcw-doors-1.0.7-mc1.19.jar | StorageDrawers-1.19-11.1.2.jar
AwesomeFlooring-Forge-1.19-2.0.1.jar | mcw-furniture-3.0.1-mc1.19.jar | supermartijn642configlib-1.1.6b-forge-mc1.19.jar
balm-4.5.0.jar | mcw-lights-1.0.4-mc1.19.jar | supermartijn642corelib-1.0.19-forge-mc1.19.jar
betteranimalsplus-1.19-11.0.7-forge.jar | mcw-roofs-2.1.2-mc1.19.jar | supplementaries-1.19-2.0.3.jar
BetterVillage-Forge-1.19-1.0.2.jar | mcw-trapdoors-1.0.7-mc1.19.jar | TerraBlender-forge-1.19-2.0.0.120.jar
BiomesOPlenty-1.19-17.0.0.143.jar | mcw-windows-2.0.3-mc1.19.jar | tombstone-8.0.4-1.19.jar
Bookshelf-Forge-1.19-14.2.10.jar | moonlight-1.19-2.0.5.jar | ToolBelt-1.19-1.19.6.jar
caelus-forge-1.19-3.0.0.3.jar | moredoors-1.19-1.27.jar | torchmaster-19.0.2-beta.jar
carryon-1.19-1.18.1.2.jar | MoreVanillaArmor-1.19-4.0.4.jar | trashslot-forge-1.19-12.0.0.jar
castle_dungeons-3.3-1.19-forge.jar | morevillagers-forge-1.19-4.0.3.jar | farmingforblockheads-forge-1.19-11.1.0.jar
catalogue-1.6.3-1.19.jar | MouseTweaks-forge-mc1.19-2.23.jar | FastLeafDecay-30.jar
cfm-7.0.0-pre34-1.19.jar | nametagtweaks_1.19.0-2.0.jar | findercompass-1.19.2.jar
charmofundying-forge-6.0.0-beta.2+1.19.jar | Oh_The_Biomes_You'll_Go-forge-1.19-2.0.0.7.jar | ForgeEndertech-1.19-10.0.3.0-build.0499.jar
citadel-1.12.6-1.19.jar | OptiFine_1.19_HD_U_H9.jar | FpsReducer2-forge-1.19-2.0.3.jar
Clumps-forge-1.19.1-9.0.0+9.jar | PigPen-Forge-1.19-9.1.3.jar | elementalcraft-1.19-5.1.0b.jar
CodeChickenLib-1.19-4.2.2.468-universal.jar | PlayerRevive_FORGE_v2.0.5_mc1.19.jar | elevatorid-1.19-1.8.6.jar
collective-1.19.0-4.30.jar | CosmeticArmorReworked-1.19.1-v1.jar | ellemes-container-library-2.0.4+1.19-forge.jar
comforts-forge-6.0.0-beta.5+1.19.jar | craftingtweaks-forge-1.19-15.0.0.jar | elytraslot-forge-6.0.0-beta.1+1.19.jar
configured-1.5.6-1.19.jar | CreativeCore_FORGE_v2.7.4_mc1.19.jar | expandedstorage-8.0.2+1.19-forge.jar
connectedglass-1.1.4b-forge-mc1.19.jar | Croptopia-1.19-FABRIC-2.0.7.jar | FallingTree-1.19-3.7.4.jar
cookingforblockheads-forge-1.19-13.2.0.jar | curios-forge-1.19-5.1.0.4.jar | FarmersDelight-1.19-1.1.2.jar
corail_woodcutter-1.19-2.4.2.jar | DarkUtilities-Forge-1.19-11.1.3.jar | DungeonCrawl-1.19-2.3.11.jar
EarthMobs-1.19-2.3.4.jar | dpanvil-1.19-4.1.0.jar | DungeonsArise-1.19-2.1.51-beta.jar
easy_villagers-1.19-1.0.8.jar |   |  

</body>
</html>

**Comment by TarantelTM** [comment]
Ok i see i need to upgrade the Code for the newest Forge Version for 1.19.
Maybe i will also add Versions for 1.19.1 and 1.19.2 but atm the code changed again dramaticly in 1.19.1 and 1.19.2.
So it will take some time.

**Comment by TarantelTM** [comment]
Should fixed in the newest Version 4.0
